### ISSUE TITLE
提示安装包已损坏

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [banli17/react-native-update-app#11]
正常安装可以，但是通过这个安装就会提示应用已损坏。

**Comment by banli17** [comment]
对原生不了解，我现在用的同事封装的库，具体 https://github.com/banli17/react-native-update-app/issues/10 。不过界面丑了点，原生的，这几个月好像没客户反应升级问题，应该没啥问题。如果用的话，再看看readme最后的使用说明和注意事项
