### ISSUE TITLE
关于app版本号

### ISSUE THREAD

**Issue by yutao98712** [banli17/react-native-update-app#2]
看到json文件里有这样一个属性：version: app 版本号，如果大于 app 当前版本号，则会弹出更新框。
这里的“当前版本号”指的是什么，在哪里设置？

**Comment by banli17** [comment]
这个框架还有点小问题，我这两天更新下，10号前更新完。比如说code-push是做热更新版本号一般不变。硬更新一般是大更新。会修改`android/app/build.gradle`里的versionName字段。比如以前是1.0版本，现在升级，就需要返回如2.0版本(2.0 > 1.0 )。

**Comment by banli17** [comment]
@yutao98712  刚刚在app里用了下，改了些东西，可以使用了。跟着文档走就可以。过些天会优化更新一些样式。

**Comment by yutao98712** [comment]
好的，thank you, 我想完成的就是检查更新的功能，应该就是你说的硬更新了，等于是把app重新装了一遍，你这里说的热更新是什么，是指不下载新的app而实现的那种内更新吗，这种方式在react native里有什么插件能实现吗？

**Comment by banli17** [comment]
@yutao98712   热更新可以用react-native-code-push，不过最好自己搭建服务器，速度快。

可以参考：https://github.com/banli17/blog/blob/3ec1367ecb3b4ad1da7b6dd5601ba0c44de5407a/static/react-native/plugs/react-native-code-push.md
最下面的参考网址
