### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by sh4msi** [banli17/react-native-update-app#3]
not work!

FAILURE: Build failed with an exception.

BUILD FAILED* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.

   > A problem occurred configuring project ':react-native-fs'.
      > Could not resolve all dependencies for configuration ':react-native-fs:classpath'.
         > Could not resolve com.android.tools.build:gradle:1.5.0.
           Required by:
               shahriz:react-native-fs:unspecified
            > Could not resolve com.android.tools.build:gradle:1.5.0.
               > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.pom'.
                  > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/1.5.0/gradle-1.5.0.pom'. Received status code 407 from server: Proxy Authentication Required

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by banli17** [comment]
seems source download fail, you can use a vpn proxy。

i create a new project，and only install this library ,it's ok !

just now i update this library to 1.1.3， you can remove your has installed version。 i  removed a function auto install dependence, now you should  manual  first install [react-native-fs](https://github.com/itinance/react-native-fs)，and then install this library。
