### ISSUE TITLE
ios更新弹出框无法弹出

### ISSUE THREAD

**Issue by simolee** [banli17/react-native-update-app#5]
ios 中获取不到本地版本，无法和更新的版本对比，导致更新弹出框无法弹出

**Comment by banli17** [comment]
@simolee  不急的话等几天。我刚刚把这个组件的安卓又更新了下。调用组件方式变了。这样可以在其它地方点版本更新按钮的时候也触发。ios的这几天我会修复下，本周会解决。

**Comment by banli17** [comment]
@simolee  可以了，刚刚改了一下发布了
