### ISSUE TITLE
打开安装apk的闪退

### ISSUE THREAD

**Issue by badxchen** [banli17/react-native-update-app#6]
android:resource="@xml/provider_paths

provider_paths的配置文件,有特殊要求么

intent.setDataAndType(apkUri, "application/vnd.android.package-archive");
reactContext.startActivity(intent);

谢谢,您的帮助, 问题找到了 ,还需要获取安装apk的权限 :  <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES"/>

**Comment by banli17** [comment]
这个文件在这个插件的`android/src/res/provider_paths.xml`里，因为我本来想把那个配置放在插件的AndroidManifest.xml里面的，但是编译不通过，所以放在了主应用的AndroidManifest里面。我有空再试试放插件里看看。

也就是自己不用新建xml文件。

如果是小米，你把那个 `设置-> 开发者工具-> 显示强制关闭`  打开，看看有没有报错信息。其它手机应该也有这个选项。

另外，你试试，不自动调用它，手动调用看看。通过点击按钮，再更新。

```
<RNUpdate ref={r=>global.$RNUpdate = r} />

onPress = async ()=>{
    $RNUpdate.updateApp( {
                "version":"1.1",
                "filename":"微信.apk",
                "url":"http://gdown.baidu.com/data/wisegame/785f37df5d72c409/weixin_1320.apk",
                "desc":["更新了一些bug", "修复了一些UI问题"]
            })
}
```

像上面这样。如果还有问题，可以加q: 867889876
