### ISSUE TITLE
报错No resource found that matches the given name 

### ISSUE THREAD

**Issue by internet5** [banli17/react-native-update-app#9]
android\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:42: error: Error: No resource found that matches the given name (at 'resource' with value '@xml/provider_paths'

**Comment by internet5** [comment]
sdk27 android8.1

**Comment by banli17** [comment]
在主项目中加入 android/src/res/xml/provider_paths.xml 文件

```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <root-path name="name" path="" />
</paths>
```
